// <auto-generated />
using System;
using ClubCordobaWallet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubCordobaWallet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("member_number_seq");

            modelBuilder.Entity("ClubCordobaWallet.Domain.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("VcJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vc_json");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("ClubCordobaWallet.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Did")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("did");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_number");

                    b.HasKey("Id");

                    b.HasIndex("Did")
                        .IsUnique();

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("MemberNumber")
                        .IsUnique();

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("ClubCordobaWallet.Domain.Entities.Credential", b =>
                {
                    b.HasOne("ClubCordobaWallet.Domain.Entities.Member", "Member")
                        .WithMany("Credentials")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ClubCordobaWallet.Domain.Entities.Member", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
